### ISSUE TITLE
Icehouse no longer available

### ISSUE THREAD

**Issue by necrogami** [jameswthorne/vagrantfiles-swift#2]
Even in EOL the RDO files are no longer available. 

Can this get updated to EL7 and a newer version of openstack that isn't end of life?

**Comment by jameswthorne** [comment]
Thanks @necrogami. I'm slowly working on updated CentOS 7 Vagrant Boxes so I can pull the latest OpenStack releases. There are known issues with adding NICs to a CentOS 7 Vagrant Box that is causing delays. I will update the GitHub repo once all that is figured out. I do not have an ETA on that though.

**Comment by necrogami** [comment]
Thanks for the update, I'm looking forward to working with this once it is updated.

**Comment by jameswthorne** [comment]
Hey @necrogami, I no longer work with OpenStack, and, as such, will not be updating these Vagrantfiles.

I have specified this in [my blog post](https://thornelabs.net/2014/07/14/install-a-stand-alone-multi-node-openstack-swift-cluster-with-virtualbox-or-vmware-fusion-and-vagrant.html) that references this GitHub repository.

Feel free to fork the GitHub repository and update as necessary for your needs.
